/**********************************************************************
   Map-N-Zap v2.x. Interface to the CYE Personal Robot
   Copyright (C) 2000, Probotics, Inc.

   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License
   as published by the Free Software Foundation; either version 2
   of the License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   General Public License for more details.Furthermore, this source code
   is distributed without any promise, implied or explicit, of
   support from Probotics, Inc.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
   02111-1307, USA.

   Probotics, Inc
   http://www.personalrobots.com
   700 River Ave #223
   Pittsburgh, PA 15212
   USA
 **********************************************************************/
#if !defined(AFX_MSIAV_H__B7A4A9A4_BC4A_11D3_A1ED_0050DA18107C__INCLUDED_)
#define AFX_MSIAV_H__B7A4A9A4_BC4A_11D3_A1ED_0050DA18107C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMSIAV wrapper class

class CMSIAV : public CWnd
{
    protected:
        DECLARE_DYNCREATE(CMSIAV)
    public:
        CLSID const& GetClsid()
        {
            static CLSID const clsid
                = { 0xb32468e3, 0xac49, 0x11d0, { 0xb1, 0xc6, 0x0, 0xaa, 0x0, 0xc1, 0xac, 0x85 } };
            return clsid;
        }
        virtual BOOL Create(LPCTSTR lpszClassName,
                            LPCTSTR lpszWindowName, DWORD dwStyle,
                            const RECT& rect,
                            CWnd* pParentWnd, UINT nID,
                            CCreateContext* pContext = NULL)
        {
            return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID);
        }

        BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
                    const RECT& rect, CWnd* pParentWnd, UINT nID,
                    CFile* pPersist = NULL, BOOL bStorage = FALSE,
                    BSTR bstrLicKey = NULL)
        {
            return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
                                 pPersist, bStorage, bstrLicKey);
        }

        // Attributes
    public:
        long GetMSInfoView();
        void SetMSInfoView(long);

        // Operations
    public:
        void MSInfoRefresh(BOOL fForSave, long* pCancel);
        BOOL MSInfoLoadFile(LPCTSTR szFileName);
        void MSInfoSelectAll();
        void MSInfoCopy();
        void MSInfoUpdateView();
        long MSInfoGetData(long dwMSInfoView, long* pBuffer, long dwLength);
        void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MSIAV_H__B7A4A9A4_BC4A_11D3_A1ED_0050DA18107C__INCLUDED_)
