/**********************************************************************
   Map-N-Zap v2.x. Interface to the CYE Personal Robot
   Copyright (C) 2000, Probotics, Inc.

   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License
   as published by the Free Software Foundation; either version 2
   of the License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   General Public License for more details.Furthermore, this source code
   is distributed without any promise, implied or explicit, of
   support from Probotics, Inc.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
   02111-1307, USA.

   Probotics, Inc
   http://www.personalrobots.com
   700 River Ave #223
   Pittsburgh, PA 15212
   USA
 **********************************************************************/
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "oleobject.h"


/////////////////////////////////////////////////////////////////////////////
// COLEObject properties

/////////////////////////////////////////////////////////////////////////////
// COLEObject operations

long COLEObject::GetIndex()
{
    long result;
    InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
    return result;
}

CString COLEObject::GetKey()
{
    CString result;
    InvokeHelper(0x2, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
    return result;
}

void COLEObject::SetKey(LPCTSTR lpszNewValue)
{
    static BYTE parms[] =
        VTS_BSTR;
    InvokeHelper(0x2, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
                 lpszNewValue);
}

CString COLEObject::GetClass()
{
    CString result;
    InvokeHelper(0x3, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
    return result;
}

long COLEObject::GetDisplayType()
{
    long result;
    InvokeHelper(0x5, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
    return result;
}

void COLEObject::SetDisplayType(long nNewValue)
{
    static BYTE parms[] =
        VTS_I4;
    InvokeHelper(0x5, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
                 nNewValue);
}

VARIANT COLEObject::GetObjectVerbs()
{
    VARIANT result;
    InvokeHelper(0x6, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
    return result;
}

VARIANT COLEObject::GetObjectVerbFlags()
{
    VARIANT result;
    InvokeHelper(0x7, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
    return result;
}

long COLEObject::GetObjectVerbsCount()
{
    long result;
    InvokeHelper(0x8, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
    return result;
}

void COLEObject::DoVerb(const VARIANT& verb)
{
    static BYTE parms[] =
        VTS_VARIANT;
    InvokeHelper(0x9, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
                 &verb);
}

long COLEObject::FetchVerbs()
{
    long result;
    InvokeHelper(0xa, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
    return result;
}
