/**********************************************************************
   Map-N-Zap v2.x. Interface to the CYE Personal Robot
   Copyright (C) 2000, Probotics, Inc. 
 
   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License
   as published by the Free Software Foundation; either version 2
   of the License, or (at your option) any later version.
 
   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   General Public License for more details.Furthermore, this source code
   is distributed without any promise, implied or explicit, of 
   support from Probotics, Inc.
 
   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  
   02111-1307, USA.
 
   Probotics, Inc
   http://www.personalrobots.com
   700 River Ave #223
   Pittsburgh, PA 15212
   USA
 **********************************************************************/
 //{{NO_DEPENDENCIES}}
 // Microsoft Developer Studio generated include file.
 // Used by RobotWorld.rc
 //
 #define IDC_VIDEOFORMATBUTTON           3
 #define IDC_VIDEODONEBUTTON             4
 #define IDD_ABOUTBOX                    100
 #define IDP_OLE_INIT_FAILED             100
 #define IDC_MHCOMMCONTROL               101
 #define ID_INDICATOR_TIME               105
 #define ID_LABELBUTTONS                 106
 #define ID_REDZONES                     107
 #define IDD_POSITIONERROR               108
 #define CG_IDR_POPUP_ROBOT_WORLD_VIEW   109
 #define ID_JOYSTICK_TIMER               110
 #define IDC_BATTERY_CHARGING_STATE      112
 #define ID_VIDEO_WINDOW                 113
 #define IDR_MAINFRAME                   128
 #define IDR_ROBOTWTYPE                  129
 #define IDR_ROBOTCONTROL                133
 #define IDW_ROBOTSTATUS                 135
 #define IDD_LABELNAME                   138
 #define IDD_MOTORCONTROLS               140
 #define IDD_CALIBRATESURFACE            141
 #define IDD_CREATECALIBRATIONWALL1      142
 #define IDD_CREATECALIBRATIONWALL2      143
 #define IDD_CREATECALIBRATIONDOORWAY2   145
 #define IDD_CREATECALIBRATIONDOORWAY1   146
 #define IDD_ESTOP                       147
 #define IDD_PROBGRIDDISP                155
 #define IDB_REDZONE                     161
 #define IDB_CALIBRATIONZONE             163
 #define IDD_RELOCATEROBOT               164
 #define IDB_ARROW1                      166
 #define IDB_ARROW2                      167
 #define IDB_ARROW3                      168
 #define IDD_CREATEVACUUMPATCH           170
 #define IDC_MMEDIT                      172
 #define IDC_MMERASE                     173
 #define IDC_MMPLACEVACUUMPATCH          174
 #define IDD_JOYSTICKCONTROL             175
 #define IDB_JOYSTICK_ORIENTATION1       176
 #define IDB_JOYSTICK_ORIENTATION2       177
 #define IDB_JOYSTICK_ORIENTATION3       178
 #define IDB_JOYSTICK_ORIENTATION4       179
 #define IDC_MM_PLACE_RED_ZONE           180
 #define IDD_CREATECALIBRATIONWALL3      183
 #define IDD_CREATECALIBRATIONWALL4      184
 #define IDB_BITMAP1                     186
 #define IDD_ROBOTCOM                    187
 #define IDB_POSITION_LABEL3             190
 #define IDD_DLG_EDIT_CAL_ZONE           191
 #define IDB_POSITION_LABEL2             192
 #define IDB_POSITION_LABEL1             193
 #define IDD_TEST_ROBOT                  194
 #define IDD_MOUSE_CONTROLS              195
 #define IDD_CALIBRATION_SUCCESSFUL      196
 #define IDD_LAYGO                       197
 #define IDC_MM_HAND                     200
 #define IDC_MM_PLACE_POSTION_LABEL      201
 #define IDC_MM_UNKNOWN_GRID             211
 #define IDC_MM_CLEAR_GRID               212
 #define IDC_MM_BLOCK_GRID               213
 #define IDW_DRAWING_TOOLS               214
 #define IDB_FINISH_LINE3                215
 #define IDC_MM_PLACE_FINISH_LINE        216
 #define IDD_PROP_ROBOT_COLOR            218
 #define IDB_ROBOT_BITMAP300             220
 #define IDB_ROBOT_BITMAP011             221
 #define IDB_ROBOT_BITMAP022             222
 #define IDB_ROBOT_BITMAP033             223
 #define IDB_ROBOT_BITMAP044             224
 #define IDB_ROBOT_BITMAP200             225
 #define IDB_ROBOT_BITMAP000             226
 #define IDD_SET_RESOLUTION              227
 #define IDD_ORIENT_HOMEBASE             228
 #define IDD_HOMEBASE_CORNER             229
 #define IDD_EDIT_LINE_PATH              232
 #define IDB_BATTERY_CHARGING            234
 #define IDB_BATTERY_CHARGED             235
 #define IDB_BATTERY_NOT_CHARGING        236
 #define IDD_PROP_GENERAL                237
 #define IDW_FLOWZAP_CONTROL             241
 #define IDI_FZC_PLAY                    253
 #define IDI_FZC_PAUSE                   254
 #define IDI_FZC_STOP                    255
 #define IDB_PRACTICE_TOOLBAR            257
 #define IDR_ROBOT_TOOLS                 260
 #define IDD_BATTERY_LOW                 264
 #define IDI_BATTERY_LOW                 265
 #define IDD_ROBOT_ERROR                 266
 #define IDD_CHECKING_WOOD_WITH_VACUUM   267
 #define IDD_HOMEBASE_FLOOR_TYPE         268
 #define IDD_CREATE_CALIBRATE_ON_SLIPPERY_FLOOR 269
 #define IDR_MAP_TOOLS                   270
 #define IDB_ROBOT_STATUS_NOT_CHARGING   275
 #define IDB_ROBOT_STATUS_CHARGING       276
 #define IDB_ROBOT_STATUS_CHARGED        277
 #define IDB_SPEEDBALL                   280
 #define IDB_FZ_EXECUTE_BACKGROUND       281
 #define IDB_FZ_STOP_ENABLED             282
 #define IDB_FZ_PLAY_ENABLED             283
 #define IDB_FZ_PAUSE_ENABLED            284
 #define IDB_FZ_STOP_DISABLED            285
 #define IDB_FZ_PLAY_DISABLED            286
 #define IDB_FZ_PAUSE_DISABLED           287
 #define IDB_FZ_SHOW_FZ_ENABLED          288
 #define IDB_FZ_SHOW_FZ_DISABLED         289
 #define IDB_DRAW_FREEHAND               291
 #define IDB_DRAW_PENS_INACTIVE          292
 #define IDB_DRAW_LINE                   293
 #define IDB_DRAW_RECTANGLE              294
 #define IDB_DRAW_WIDTHS_INACTIVE        295
 #define IDB_DRAW_PEN_CLEAR_ACTIVE       296
 #define IDB_DRAW_PEN_OBSTACLE_ACTIVE    297
 #define IDB_DRAW_PEN_UNKNOWN_ACTIVE     298
 #define IDB_DRAW_WIDTH_SMALL_ACTIVE     299
 #define IDB_DRAW_WIDTH_MEDIUM_ACTIVE    300
 #define IDB_DRAW_WIDTH_LARGE_ACTIVE     301
 #define IDB_DRAW_WIDTH_XLARGE_ACTIVE    302
 #define IDB_MAP_BAR                     303
 #define IDD_MAP_BAR                     304
 #define IDB_VELOCITY_TORQUE             305
 #define IDD_VELOCITY_TORQUE             306
 #define IDC_MM_DRAW_LINE                307
 #define IDC_MM_DRAW_FREEHAND            308
 #define IDC_MM_DRAW_RECTANGLE           309
 #define IDC_MM_SEARCH                   310
 #define IDC_MM_MOVE_ROBOT               311
 #define IDB_FZ_STOP_PUSHED              312
 #define IDB_FZ_PLAY_PUSHED              313
 #define IDB_FZ_PAUSE_PUSHED             314
 #define IDB_FZ_SHOW_FZ_PUSHED           315
 #define IDB_SPLASH                      316
 #define IDD_SPLASH                      317
 #define IDD_COM_PORT_SEARCH             318
 #define IDD_COM_PORT_SEARCH_FAILED      319
 #define IDD_COM_PORT_SEARCH_STATUS      321
 #define IDD_PROP_FLOOR                  322
 #define IDD_CYE_SAMPLE                  323
 #define IDB_SMALL_GREY_ARROW            325
 #define IDB_LARGE_GREY_ARROW            326
 #define IDB_MEDIUM_BLACK_ARROW          327
 #define IDB_MEDIUM_GREY_ARROW           328
 #define IDB_SMALL_BLACK_ARROW           329
 #define IDB_BITMAP7                     330
 #define IDB_LARGE_BLACK_ARROW           330
 #define IDB_POSITION_LABEL35            333
 #define IDB_POSITION_LABEL11            334
 #define IDB_POSITION_LABEL12            335
 #define IDB_POSITION_LABEL13            336
 #define IDB_POSITION_LABEL14            337
 #define IDB_POSITION_LABEL15            338
 #define IDB_POSITION_LABEL20            339
 #define IDB_POSITION_LABEL21            340
 #define IDB_POSITION_LABEL22            341
 #define IDB_POSITION_LABEL23            342
 #define IDB_POSITION_LABEL24            343
 #define IDB_POSITION_LABEL10            344
 #define IDB_POSITION_LABEL33            345
 #define IDB_POSITION_LABEL30            346
 #define IDB_POSITION_LABEL31            347
 #define IDB_POSITION_LABEL32            348
 #define IDB_POSITION_LABEL25            349
 #define IDB_POSITION_LABEL34            350
 #define IDB_FINISH_LINE37               351
 #define IDB_FINISH_LINE10               352
 #define IDB_FINISH_LINE11               353
 #define IDB_FINISH_LINE12               354
 #define IDB_FINISH_LINE13               355
 #define IDB_FINISH_LINE14               356
 #define IDB_FINISH_LINE15               357
 #define IDB_FINISH_LINE16               358
 #define IDB_FINISH_LINE17               359
 #define IDB_FINISH_LINE2                360
 #define IDB_FINISH_LINE20               361
 #define IDB_FINISH_LINE21               362
 #define IDB_FINISH_LINE22               363
 #define IDB_FINISH_LINE36               364
 #define IDB_FINISH_LINE23               365
 #define IDB_FINISH_LINE24               366
 #define IDB_FINISH_LINE25               367
 #define IDB_FINISH_LINE26               368
 #define IDB_FINISH_LINE27               369
 #define IDB_FINISH_LINE30               371
 #define IDB_FINISH_LINE31               372
 #define IDB_FINISH_LINE32               373
 #define IDB_FINISH_LINE33               374
 #define IDB_FINISH_LINE34               375
 #define IDB_FINISH_LINE35               376
 #define IDB_FINISH_LINE1                377
 #define IDB_TIMER_TOP                   378
 #define IDB_TIMER_LEFT                  379
 #define IDB_TIMER_RIGHT                 380
 #define IDB_TIMER_BOTTOM                381
 #define IDB_START_LINE3                 382
 #define IDB_START_LINE2                 383
 #define IDB_START_LINE1                 384
 #define IDR_DRAWING_TOOLS               385
 #define IDD_CREATE_HOME_ON_WOOD         387
 #define IDD_GRID_DISPLAY                396
 #define IDC_MM_PLACE_START_LINE         397
 #define IDC_MM_PLACE_LINE_PATH          398
 #define IDD_VERSION_WARNING             399
 #define IDD_MEASURING_CARPET_DENSITY    400
 #define IDD_EXECUTABLE_OBJECT_GENERAL_PROP 401
 #define IDD_LOW_RADIO_LEVEL             402
 #define IDB_LAYGO_DEFAULT               404
 #define IDB_ROBOT_BITMAP_CHROME         408
 #define IDR_ROBOT_EXTERNALS             409
 #define IDW_ROBOT_EXTERNALS             411
 #define IDB_ROBOT_EXTERNALS_OFF         413
 #define IDB_ROBOT_EXTERNALS_ON          414
 #define IDD_ADD_ROBOT                   415
 #define IDD_ADD_HOMEBASE                417
 #define IDD_CYE_PERSONA                 418
 #define IDD_CYE_PERSONA_BEHAVIOR        419
 #define IDD_CYE_PERSONA_MOTION          421
 #define IDD_CYE_PERSONA_SONG            422
 #define IDD_VIDEO                       424
 #define IDC_CHKOBSTAVOID                1006
 #define IDC_CHK_ENABLE_LEARN_ROOM       1006
 #define IDC_CHKAUTOCAL                  1007
 #define IDC_CHK_AUTOCALIBRATE           1007
 #define IDC_BUT_SET_PATH_BUFFER         1008
 #define IDC_BUT_FZPAUSE                 1008
 #define IDC_TEST_INPUT                  1008
 #define IDC_LeftRight                   1008
 #define IDC_EDTLABELNAME                1009
 #define IDC_EDTOBSTACLE                 1010
 #define IDC_EDTM0PWM                    1011
 #define IDC_EDTM1PWM                    1012
 #define IDC_BUTSETPWM                   1013
 #define IDC_EDTHEADING                  1014
 #define IDC_BUTSETHEADING               1015
 #define IDC_BUTSTOPMOTORS               1016
 #define IDC_CHKFLIPHANDLE               1017
 #define IDC_BUTSHOWHEADING              1018
 #define IDC_EDTM0SPEED                  1019
 #define IDC_EDTM1SPEED                  1020
 #define IDC_BUTSETSPEED                 1021
 #define IDC_BUTSTOPMOTORS2              1022
 #define IDC_EDTCURRENTHEADING           1023
 #define IDC_BUTTON1                     1024
 #define IDC_BUTTURNRIGHT                1025
 #define IDC_EDTSTRAIGHTHEADING          1025
 #define IDC_BUTTURNLEFT                 1026
 #define IDC_BUTSETSTRAIGHTHEADING       1026
 #define IDC_BUTFOLLOWPATH               1027
 #define IDC_BUTGOSTRAIGHT               1028
 #define IDC_EDTPATHRESULT               1029
 #define IDC_BUTCALIBRATEHEADING         1030
 #define IDC_EDTTOTALENCODERTICKS        1031
 #define IDC_BUTDO360                    1033
 #define IDC_BUTRESETPOSITION            1036
 #define IDC_BUTCREATEDOORWAY            1037
 #define IDC_BUTCALIBRATE                1038
 #define IDC_BUTCREATEWALL               1039
 #define IDC_BUTSENDDEFAULTCORRECTION    1040
 #define IDC_EDTMAXSPEED                 1041
 #define IDC_BUTSETMAXSPEED              1042
 #define IDC_CHKSENSITIVEOBSTACLE        1043
 #define IDC_BUTRESETPOSITION2           1043
 #define IDC_EDTKHEADERR                 1044
 #define IDC_BUTRESETPOSITION3           1045
 #define IDC_ESTOP                       1046
 #define IDC_EDTM0VELMEAS                1047
 #define IDC_EDTM1VELMEAS                1048
 #define IDC_EDTM0ACCELERATION           1049
 #define IDC_EDTM1ACCELERATION           1050
 #define IDC_EDTM0AD                     1061
 #define IDC_EDTM1AD                     1062
 #define IDC_CHKRECORDINFO               1065
 #define IDC_EDTM0PWMMEAS                1066
 #define IDC_EDTM1PWMMEAS                1067
 #define IDC_BUTPURGERINGBUFFER          1068
 #define IDC_RADOBSHIGHSENS              1069
 #define IDC_RADOBSMEDSENS               1070
 #define IDC_RADOBSLOWSENS               1071
 #define IDC_RADOBSNONE                  1072
 #define IDC_EDT_BATTERY_AD              1073
 #define IDC_SCRROBOTHEADING             1074
 #define IDC_EDTROBOTHEADING             1075
 #define IDC_BUTSHOWPOSITION             1076
 #define IDC_EDTX                        1077
 #define IDC_EDTH                        1079
 #define IDC_EDTY                        1080
 #define IDC_EDTM0ENCODER                1081
 #define IDC_EDTM1ENCODER                1082
 #define IDC_BUTNOCORRECTION             1083
 #define IDC_RADTOPRGT                   1084
 #define IDC_RADRGTBOT                   1085
 #define IDC_RADBOTLFT                   1086
 #define IDC_RADLFTTOP                   1087
 #define IDC_RADLFTBOT                   1088
 #define IDC_RADBOTRGT                   1089
 #define IDC_RADTOPLFT                   1090
 #define IDC_RADRGTTOP                   1091
 #define IDC_EDTPATHWIDTH                1092
 #define IDC_EDTTURNDIAMETER             1093
 #define IDC_EDTKP                       1094
 #define IDC_EDTKI                       1095
 #define IDC_EDTKD                       1096
 #define IDC_EDTKB                       1097
 #define IDC_EDTKPWM                     1098
 #define IDC_BUTSENDMOTORCONTROLCONSTANTS 1099
 #define IDC_BUTSENDMOTOCONDEFAULTS      1100
 #define IDC_EDTHANDLELENGTH             1101
 #define IDC_EDTBUZZERFREQUENCY          1102
 #define IDC_BUTSENDBUZZER               1103
 #define IDC_SLI_JOYSTICKRESPONSIVENESS  1105
 #define IDC_SLI_TURNGAIN                1106
 #define IDC_BUT_SET_DEFAULTS            1112
 #define IDC_SCR_JOYSTICK_ORIENTATION    1114
 #define IDC_EDT_JOYSTICK_ORIENTATION    1115
 #define IDC_CHK_JOYSTICK_ENABLE         1118
 #define IDC_RAD_JOYSTICK_ROBOT_COORDS   1119
 #define IDC_RAD_JOYSTICK_WORLD_COORDS   1120
 #define IDC_RAD_JOYSTICK_TORQUE_CONTROL 1121
 #define IDC_RAD_JOYSTICK_VELOCITY_CONTROL 1122
 #define IDC_EDT_M0OBST                  1124
 #define IDC_EDT_M1OBST                  1125
 #define IDC_EDT_PARM1                   1126
 #define IDC_EDT_PARM2                   1127
 #define IDC_EDT_PARM3                   1128
 #define IDC_EDT_PARM4                   1129
 #define IDC_BUT_SET                     1130
 #define IDC_BUT_PARM_DEFAULT            1131
 #define IDC_EDT_CORRECTION              1132
 #define IDC_BUT_SEND_CORRECTION         1133
 #define IDC_BUT_WRITE_PROB_GRID         1134
 #define IDC_EDT_START_X                 1135
 #define IDC_EDT_START_Y                 1136
 #define IDC_EDT_ITERATIONS              1137
 #define IDC_EDT_REPEAT                  1138
 #define IDC_EDT_END_X                   1139
 #define IDC_EDT_END_Y                   1140
 #define IDC_BUT_FIND_PATH               1141
 #define IDC_EDT_MIN_FOUND               1142
 #define IDC_EDT_AVG_FOUND               1143
 #define IDC_EDT_START_DIST              1144
 #define IDC_EDT_END_DIST                1145
 #define IDC_EDT_FREE_DIST               1146
 #define IDC_CHK_STOP_PATH               1147
 #define IDC_EDT_FIND_CAL_ZONE_X         1148
 #define IDC_EDT_FIND_CAL_ZONE_Y         1149
 #define IDC_BUT_FIND_CAL_ZONE           1150
 #define IDC_EDT_NAME                    1151
 #define IDC_RRRCOMCTRL1                 1152
 #define IDC_CYECOMCTRL1                 1152
 #define IDC_EDT_VELOCITY_DIRECTION_HEADING 1154
 #define IDC_EDT_VELOCITY_DIRECTION_VELOCITY 1155
 #define IDC_BUT_SET_VELOCITY_DIRECTION  1156
 #define IDC_SCR_MAX_SPEED               1157
 #define IDC_BUT_CREATE_CAL_WALL         1160
 #define IDC_BUT_CREATE_CAL_CORNER       1161
 #define IDC_BUT_CREATE_CAL_DOOR         1162
 #define IDC_EDT_CALZONE_NAME            1163
 #define IDC_BUT_TEST_MOTORS             1164
 #define IDC_CHK_SEND_POSITION           1165
 #define IDC_CHK_SEND_VELOCITIES         1166
 #define IDC_CHK_SEND_AD                 1167
 #define IDC_CHK_SEND_ACCEL              1168
 #define IDC_BUT_SEND_VALUES             1169
 #define IDC_BUT_FREE_WHEEL_TEST         1170
 #define IDC_BUT_M1FORWARD               1171
 #define IDC_BUT_M0BACKWARD              1172
 #define IDC_BUT_M1BACKWARD              1173
 #define IDC_BUT_STOP_MOTORS             1174
 #define IDC_BUT_M0FORWARD               1175
 #define IDC_BUT_AGAINST_WALL_TEST       1176
 #define IDC_BUT_ROTATE_TEST             1177
 #define IDC_VACUUM_PATCH_BOUNDS         1179
 #define IDC_EDT_DX                      1180
 #define IDC_EDT_DY                      1181
 #define IDC_EDT_DH                      1182
 #define IDC_CHK_DONT_SHOW_AGAIN         1183
 #define IDC_DONTSHOW                    1188
 #define IDC_RICHEDIT5                   1192
 #define IDC_INFO                        1192
 #define IDC_RICHTEXTCTRL1               1196
 #define IDC_INFO_VIEWER                 1196
 #define IDC_RTX_CYE_SAMPLE_TEXT         1196
 #define IDC_RADIO1                      1197
 #define IDC_RADIO2                      1198
 #define IDC_RADIO3                      1199
 #define IDC_RADIO4                      1200
 #define IDC_RADIO5                      1201
 #define IDC_RADIO6                      1202
 #define IDC_TAB1                        1203
 #define IDC_BMP00                       1205
 #define IDC_BMP000                      1205
 #define IDC_BMP01                       1206
 #define IDC_BMP011                      1206
 #define IDC_BMP02                       1207
 #define IDC_BMP022                      1207
 #define IDC_BMP03                       1208
 #define IDC_BMP033                      1208
 #define IDC_BMP04                       1209
 #define IDC_BMP044                      1209
 #define IDC_BMP05                       1210
 #define IDC_BMP200                      1210
 #define IDC_BMP06                       1211
 #define IDC_BMP300                      1211
 #define IDC_BMP07                       1212
 #define IDC_BMP_CHROME                  1212
 #define IDC_BMP08                       1213
 #define IDC_CMB_DISPLAY_RESOLUTION      1217
 #define IDC_BUT_ON                      1218
 #define IDC_BMP_LAYGO_IMAGE             1219
 #define IDC_RAD_0                       1221
 #define IDC_RAD_90                      1222
 #define IDC_RAD_180                     1223
 #define IDC_RAD_270                     1224
 #define IDC_BUT_BACK                    1229
 #define IDC_EDT_LINE_PATH_NAME          1230
 #define IDC_RAD_LEFT                    1231
 #define IDC_RAD_RIGHT                   1232
 #define IDC_FRM_BITMAP                  1233
 #define IDC_CHK_CORNER_CALIBRATION      1234
 #define IDC_EDT_PARM5                   1235
 #define IDC_EDT_PARM6                   1236
 #define IDC_EDT_PARM7                   1237
 #define IDC_EDT_PARM8                   1238
 #define ID_EDT_BATTERY_LEVEL            1241
 #define IDC_RAD_SLIPPERY_FLOOR          1242
 #define IDC_RAD_CARPET_FLOOR            1243
 #define IDC_CHK_SHOW_CALIBRATION_RESULTS 1244
 #define ID_EDT_RADIO_LEVEL              1249
 #define IDC_EDT_PATH_BUFFER             1250
 #define ID_COM_FLOWZAP_FILE             1254
 #define IDC_ANIMATE1                    1258
 #define IDC_EDT_ROBOT_SOFTWARE_REV      1259
 #define IDC_EDT_ROBOT_RUN_TIME          1260
 #define IDC_EDT_ERROR_TEXT              1261
 #define IDC_ICO_ERROR                   1262
 #define IDC_CHK_INTERMITTENT_BEEP       1263
 #define IDC_WOOD_FLOOR                  1265
 #define IDC_THIN_CARPET_FLOOR           1266
 #define IDC_THICK_CARPET_FLOOR          1267
 #define IDC_RAD_WOOD_FLOOR              1268
 #define IDC_RAD_THIN_CARPET_FLOOR       1269
 #define IDC_RAD_THICK_CARPET_FLOOR      1270
 #define IDC_BUT_NEXT                    1271
 #define IDC_LEFT_VELOCITY               1281
 #define IDC_RIGHT_VELOCITY              1282
 #define IDC_LEFT_TORQUE                 1283
 #define IDC_RIGHT_TORQUE                1284
 #define IDC_EDT_COM_PORT                1287
 #define IDC_CHK_LEARN_ROOM              1288
 #define IDC_BUT_POWER_OFF               1289
 #define IDC_SCR_NORMAL_SLIP_PERCENT     1290
 #define IDC_SCR_THICK_SLIP_PERCENT      1291
 #define IDC_EDT_NORMAL_SLIP_PERCENT     1292
 #define IDC_EDT_THICK_SLIP_PERCENT      1293
 #define ID_DRAW_LINE                    1295
 #define ID_DRAW_FREEHAND                1296
 #define ID_DRAW_RECTANGLE               1297
 #define ID_DRAW_PEN_SIZE                1298
 #define ID_DRAW_PEN_STYLE               1299
 #define IDC_BUT_ROBOT_TEST              1300
 #define IDC_EDIT1                       1301
 #define IDC_ANALOG_INPUT                1301
 #define IDC_EDT_VACUUMING_SPEED         1301
 #define IDC_NAME                        1301
 #define IDC_EDT_APPROX_SLIP_COMP        1301
 #define IDC_EDT_EXTERNAL_INPUT          1301
 #define IDC_BUT_REQUEST_ANALOG_INPUT    1302
 #define IDC_CHK_ROBOT_ANIMATION         1303
 #define IDC_SPLASH_BMP                  1304
 #define IDC_ADJUST_CHECKPOINT           1307
 #define IDC_BUT_FZPLAY                  1308
 #define IDC_BUT_FZSTOP                  1309
 #define IDC_BUT_FZSHOW                  1310
 #define IDC_Ramped                      1311
 #define IDC_CHK_ANIMATE_ROBOT           1312
 #define IDC_BUT_CREATE_HOME_BASE        1313
 #define IDC_BUT_FIND_SLIP_COMPENSATION  1314
 #define IDC_SCR_CORNER_SIZE             1315
 #define IDC_EDT_CORNER_SIZE             1316
 #define IDC_STA_NAME                    1320
 #define IDC_EDT_OUTPUT                  1321
 #define IDC_COM_NUMBER_OF_CLAPS         1322
 #define IDC_TEST_MICROPHONE             1324
 #define IDC_EDT_MICROPHONE_VOLUME       1328
 #define IDC_COM_ROBOT_STYLE             1329
 #define IDC_BMP_ORANGE                  1330
 #define IDC_BMP_YELLOW                  1331
 #define IDC_BMP_BLACK                   1332
 #define IDC_EDT_ADD_HOMEBASE_INSTRUCTIONS 1334
 #define IDC_CHK_ENABLE_DANCING          1335
 #define IDC_ShowMotion                  1336
 #define IDC_Jittery1                    1337
 #define IDC_Meander                     1338
 #define IDC_Impatient3                  1339
 #define IDC_Content1                    1340
 #define IDC_Mad1                        1341
 #define IDC_Impatient1                  1342
 #define IDC_Impatient2                  1343
 #define IDC_Jittery2                    1344
 #define IDC_Quirky1                     1345
 #define IDC_Content2                    1346
 #define IDC_Content3                    1347
 #define IDC_Content4                    1348
 #define IDC_Spiral                      1349
 #define IDC_SpinnSway                   1350
 #define IDC_Eight                       1351
 #define IDC_Cross                       1352
 #define IDC_Spinn                       1353
 #define IDC_Square                      1354
 #define IDC_Nudge                       1355
 #define IDC_ZigZag                      1356
 #define IDC_Abrupt                      1357
 #define IDC_SadTune                     1357
 #define IDC_SmoothTune                  1358
 #define IDC_AgressiveTune1              1359
 #define IDC_AgressiveTune2              1360
 #define IDC_ContentTune1                1361
 #define IDC_ContentTune2                1362
 #define IDC_BoredTune1                  1363
 #define IDC_BoredTune2                  1364
 #define IDC_BoredTune3                  1365
 #define IDC_SwayTune                    1366
 #define IDC_AcknowledgeTune             1367
 #define IDC_JitteryTune1                1368
 #define IDC_JitteryTune2                1369
 #define IDC_ContentTune3                1370
 #define IDC_QuirkyTune2                 1371
 #define IDC_QuirkyTune1                 1372
 #define IDC_ShowBehavior                1373
 #define IDC_TestTune                    1373
 #define IDC_ShowSong                    1374
 #define IDC_Agressive1                  1375
 #define IDC_Agressive2                  1376
 #define IDC_Quirky2                     1377
 #define IDC_Wiggle                      1378
 #define IDC_Snake                       1379
 #define IDC_Gaits                       1380
 #define IDC_VIDEOSOURCEBUTTON           1381
 #define IDC_VIDEODISPLAYBUTTON          1382
 #define ID_GOHOME                       32771
 #define ID_SEARCHAREA                   32772
 #define ID_SEARCHWALLLEFT               32773
 #define ID_SEARCHWALLRIGHT              32774
 #define ID_VACUUM                       32775
 #define ID_BLOCKAREA                    32776
 #define ID_PLACELABEL                   32777
 #define ID_RUNPROGRAM                   32778
 #define ID_VIEW_ROBOTCONTROLS           32779
 #define ID_VIEW_ROBOTSTATUS             32780
 #define ID_CENTERROBOT                  32782
 #define ID_STOP                         32783
 #define ID_CALIBRATIONSURFACE           32784
 #define ID_BUTTON32785                  32785
 #define ID_CALIBRATESURFACE             32786
 #define ID_CREATECALIBRATIONWALL        32787
 #define ID_CREATECALIBRATIONDOORWAY     32788
 #define ID_VIEW_MOTORCONTROLS           32789
 #define ID_ZOOM100                      32791
 #define ID_ZOOM200                      32792
 #define ID_ZOOM400                      32793
 #define ID_MOUSEERASE                   32794
 #define ID_MOUSEDEFAULT                 32795
 #define ID_MOUSEMOVE                    32796
 #define ID_MMMOVE                       32797
 #define ID_MMDEFAULT                    32798
 #define ID_MMERASE                      32799
 #define ID_VIEW_LABELS                  32800
 #define ID_VIEW_REDZONES                32801
 #define ID_VIEW_PROPERTIES              32802
 #define ID_EDIT_PROPERTIES              32803
 #define ID_VIEW_JOYSTICK_CONTROLS       32810
 #define ID_VIEW_VACUUM_PATCHES          32812
 #define ID_MM_BLOCK_GRID                32813
 #define ID_BUTTON32814                  32814
 #define ID_BUTTON32815                  32815
 #define ID_MM_UNKNOWN_GRID              32816
 #define ID_MM_CLEAR_GRID                32817
 #define ID_VIEW_FLOWZAP                 32818
 #define ID_VIEW_TEST_ROBOT              32819
 #define ID_VIEW_MOUSE_CONTROLS          32821
 #define ID_VIEW_POSITION_SPOTS          32822
 #define ID_HELP_RESETLAYGO              32823
 #define ID_HELP_DISABLELAYGO            32825
 #define ID_VIEW_DRAWING_TOOLS           32826
 #define ID_MM_PLACE_FINISH_LINE         32827
 #define ID_VIEW_SETTINGS                32828
 #define ID_POWER_OFF                    32829
 #define ID_LINE_PATH                    32830
 #define ID_VACUUM_ATTACHED              32831
 #define ID_LOAD_TOOLBARS                32835
 #define ID_SAVE_TOOLBARS                32836
 #define ID_MMMOVE_ROBOT                 32845
 #define ID_VIEW_ZAP_CONTROLS            32846
 #define ID_VIEW_MAP_OBJECTS_TOOLBAR     32847
 #define ID_VIEW_INSTRUMENT_PANEL        32848
 #define ID_HELP_LAYGO_SHOW_TIP1         32849
 #define ID_HELP_LAYGO_SHOW_TIP2         32850
 #define ID_HELP_LAYGO_SHOW_TIP3         32851
 #define ID_HELP_LAYGO_SHOW_TIP4         32852
 #define ID_HELP_LAYGO_SHOW_TIP6         32854
 #define ID_HELP_LAYGO_SHOW_TIP7         32855
 #define ID_HELP_LAYGO_SHOW_TIP8         32856
 #define ID_HELP_LAYGO_SHOW_TIP9         32857
 #define ID_HELP_LAYGO_SHOW_TIP10        32858
 #define ID_HELP_LAYGO_SHOW_TIP11        32859
 #define ID_HELP_LAYGO_SHOW_TIP5         32860
 #define ID_VIEW_LINE_PATHS              32861
 #define ID_HELP_SAMPLES_CYETRUCK        32863
 #define ID_HELP_SAMPLES_CYESERVE        32864
 #define ID_HELP_SAMPLES_CYEPUP          32865
 #define ID_HELP_SAMPLES_CYECLOCK        32866
 #define ID_HELP_SAMPLES_CYEPOST         32867
 #define ID_HELP_SAMPLES_CYEGUIDE        32868
 #define ID_HELP_SAMPLES_CYEPATROL       32869
 #define ID_VIEW_RULER_GRID              32871
 #define ID_MM_PLACE_START_LINE          32875
 #define ID_HELP_LAYGO_SHOWTIP12         32876
 #define ID_HELP_LAYGO_SHOW_TIP12        32877
 #define ID_HELP_LAYGO_SHOW_DANGER_ZONES_TIP 32877
 #define ID_EDIT_DELETE                  32878
 #define ID_DRAW_PEN_OBSTACLE            32883
 #define ID_DRAW_PEN_UNKNOWN             32884
 #define ID_DRAW_PEN_FREE                32885
 #define ID_DRAW_PEN_WIDTH1              32886
 #define ID_DRAW_PEN_WIDTH2              32887
 #define ID_DRAW_PEN_WIDTH3              32888
 #define ID_DRAW_PEN_WIDTH4              32889
 #define ID_DRAW_PEN_CLEAR               32890
 #define ID_ROBOT_FORWARD                32891
 #define ID_ROBOT_BACK                   32892
 #define ID_ROBOT_ROTATE_LEFT            32893
 #define ID_ROBOT_ROTATE_RIGHT           32894
 #define ID_ADJUST_CHECKPOINT            32895
 #define ID_HELP_LAYGO_SHOW_WELCOME_TIP  32896
 #define ID_HELP_LAYGO_SHOW_ROBOT_COLOR_TIP 32897
 #define ID_HELP_LAYGO_SHOW_COM_PORT_SEARCH_TIP 32898
 #define ID_HELP_LAYGO_SHOW_CREATE_HOMEBASE_TIP 32899
 #define ID_HELP_LAYGO_SHOW_NAVIGATE_TIP 32900
 #define ID_HELP_LAYGO_SHOW_OCCUPANCY_GRID_TIP 32901
 #define ID_HELP_LAYGO_SHOW_POSITION_UNCERTAINTY_TIP 32902
 #define ID_HELP_LAYGO_SHOW_CHECKPOINT_TIP 32903
 #define ID_HELP_LAYGO_SHOW_ADDITIONAL_CHECKPOINT_TIP 32904
 #define ID_HELP_LAYGO_SHOW_HOTPOINT_TIP 32905
 #define ID_HELP_LAYGO_SHOW_VACUUMPATHS_TIP 32906
 #define ID_HELP_LAYGO_SHOW_FLOWZAP_TIP  32907
 #define ID_EXTERNAL_OUTPUT_OFF          32908
 #define ID_EXTERNAL_OUTPUT_ON           32910
 #define ID_VIEW_ADD_ROBOT               32912
 #define ID_VIEW_ADD_HOMEBASE            32913
 #define ID_VIEW_CYE_PERSONA             32914
 #define ID_SHOW_VIDEO_BUTTON            32915
 #define IDS_ERR_SQUARE_TO_WALL          61459
 #define IDS_ERR_PATH_GENERAL_ERROR      61460
 #define IDS_ERR_PATH_NO_OBSTACLE        61461
 #define IDS_ERR_PATH_NO_TIMEOUT         61462
 #define IDS_ERR_PATH_NO_ESTOP           61463
 #define IDS_ERR_PATH_TIMEOUT            61464
 #define IDS_ERR_PATH_UNEXPECTED_OBSTACLE 61465
 
 // Next default values for new objects
 // 
 #ifdef APSTUDIO_INVOKED
 #ifndef APSTUDIO_READONLY_SYMBOLS
 #define _APS_3D_CONTROLS                     1
 #define _APS_NEXT_RESOURCE_VALUE        425
 #define _APS_NEXT_COMMAND_VALUE         32916
 #define _APS_NEXT_CONTROL_VALUE         1383
 #define _APS_NEXT_SYMED_VALUE           114
 #endif
 #endif
