#define main_index	1
#define HID_HT_NOWHERE	2
#define AFX_HIDP_default	3
#define HID_APP_ABOUT_CYECOM	4
#define Version_Property	5
#define X_Property	6
#define Y_Property	7
#define Heading_Property	8
#define RadioLevel_Property	9
#define BatteryLevel_Property	10
#define ResponseTimeout_Property	11
#define RetryLimit_Property	12
#define CommState_Property	13
#define RightCurrent_Property	14
#define LeftCurrent_Property	15
#define RightVelocity_Property	16
#define LeftVelocity_Property	17
#define NumRobots_Property	18
#define SetHeadingCorrectionFactor_Method	19
#define SetFlipHandle_Method	20
#define TurnTo_Method	21
#define SetPWM_Method	22
#define Stop_Method	23
#define Pause_Method	24
#define Resume_Method	25
#define SetBuzzerFrequency_Method	26
#define SetBuzzerOn_Method	27
#define FollowPath_Method	28
#define SetHandleLength_Method	29
#define SetMotorControlConstants_Method	30
#define MoveCurve_Method	31
#define MoveStraight_Method	32
#define SetMaxSpeed_Method	33
#define SetWheelVelocities_Method	34
#define SetObstacleSensitivity_Method	35
#define MoveTo_Method	36
#define LoadPathSegment_Method	38
#define MoveDirection_Method	39
#define RequestState_Method	40
#define PowerDown_Method	41
#define SendMessage_Method	42
#define GetCommPort_Method	43
#define SetCommPort_Method	44
#define SquareToWall_Method	45
#define SetFeelingMotor_Method	46
#define CornerCalibrate_Method	47
#define FindHomeBase_Method	48
#define SetHeadingDestination_Method	49
#define SetEnableObstacleBounce_Method	50
#define SetRAMData_Method	51
#define SetRobotOnSeconds_Method	52
#define SetIntermittentBeep_Method	53
#define AddToPosition_Method	54
#define AddToHeading_Method	55
#define SetExternalOutput_Method	56
#define RequestExternalInput_Method	57
#define SetPosition_Method	58
#define RadioLevelChange_Event	59
#define BatteryLow_Event	60
#define ObstacleDetected_Event	61
#define NudgeDetected_Event	62
#define NewPathSegmentRequest_Event	63
#define RobotError_Event	64
#define OnHomeBase_Event	65
#define RobotStatusChange_Event	66
#define BatteryChargingStateChange_Event	67
#define UnknownMessage_Event	68
#define CommStateChange_Event	69
#define TaskResult_Event	70
#define SoftwareRevNumber_Event	71
#define RobotOn_Event	72
#define RobotOnTime_Event	73
#define ExternalInput_Event	74
#define NumPoints_Property	75
#define CyePath_X_Property	76
#define CyePath_Y_Property	77
#define CyePath_Object	78
#define CyeCom_Control	79
#define Robot_Header	37
#define Robot_Coordinates	80
#define Paths	81
#define CyeCom_Test	82
#define CheckPoints	83
#define Check_Points	84
